on:
 pull_request:
 push:
  branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Fetch the latest commit
    - name: Checkout
      uses: actions/checkout@v2

    # Setup Node.js using the appropriate version
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    # Install package dependencies
    - name: Install
      run: npm ci

    # Run tests
    - name: Lint
      run: npm run lint

    # Run tests
    - name: Test
      run: npm test

    - name: Codecov
      uses: codecov/codecov-action@v1.2.1
  release:
    # Only release on push to master
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    # Waits for test jobs for each Node.js version to complete
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
